### ISSUE TITLE
Rename or Remove Flurry CrashReporter

### ISSUE THREAD

**Issue by zulfishah** [flurry/FlurrySwiftPackage#10]
Hi,
I am using SPM for Flurry for just analytics, and don't want to include the crash reporting functionality, since I already have that through a different package (AppCenter). That package has a dependency on PLCrashReporter, which has an internal framework called "CrashReporter". And Flurry also seems to produce a package called "CrashReporter", which also seems to depend upon "CrashReporter" framework. The problem is that the name seems to clash, and I'm getting an error in Xcode when I try to add Flurry:

> multiple targets named 'CrashReporter' in: 'flurryswiftpackage', 'plcrashreporter'

Is there a way to fix this? I wish I could just exclude the Crash Reporting dependency in the Flurry library.

**Comment by flurrydev** [comment]
@zulfishah We will be releasing Flurry 12.0 in about two weeks, and we plan to offer a variation of Flurry that does not depend on the CrashReporter. I'll update the thread when it is available.

**Comment by zulfishah** [comment]
Thanks. Is there a temporary fix for this for the meantime?

**Comment by hatfinch** [comment]
I'm having the same issue as @zulfishah, so I'm commenting here to follow this topic.
@flurrydev Any chance of upgrading "Flurry SDK - Swift Package beta" to "Flurry SDK - Swift Package stable"?

**Comment by hatfinch** [comment]
Bump!

**Comment by flurrydev** [comment]
We have made available a build of Flurry 12.0.0 that does not require the CrashReporter.xcframework. To use this version choose the exact version 12.0.0-lite or use branch br_12.0.0-lite

With the release of 12.0.0 our Swift Package is no longer a beta. Note our official Cocoapods release now uses the same xcframeworks we are using here in SPM.
