### ISSUE TITLE
arm64 missing in watchOS simulator binary

### ISSUE THREAD

**Issue by mfclarke-ts** [flurry/FlurrySwiftPackage#11]
Hi,

It looks like arm64 is missing for the watchOS simulator binary in Flurry.xcframework. This causes Xcode to skip linking when building for Watch simulator, and build fails with symbols not defined.

I'm using the 12.0.0 release and building an iPhone app with Watch extension on Xcode 13.3.

The workaround for now is to wrap calls to `FlurryWatch` in `#if !targetEnvironment(simulator)`. But it would be great not to need to do this, and to be able to test our Flurry tracking in simulator.

Thanks

Edit: This PR originally added arm64 support to the xcframeworks: https://github.com/flurry/FlurrySwiftPackage/pull/6

**Comment by flurrydev** [comment]
We'll be releasing a fix for this issue at the beginning of next week.

**Comment by flurrydev** [comment]
This issue is resolved in Flurry v12.0.1 - let us know if you have any issues.

**Comment by mfclarke-ts** [comment]
Many thanks, works fine!
