### ISSUE TITLE
Build error on M1 Mac when building for simulator

### ISSUE THREAD

**Issue by KyLeggiero** [flurry/FlurrySwiftPackage#3]
As you know, the M1 SoC is based on arm64, so its iOS Simulator is also arm64. However, the included simulator build is for i386 and x86_64.

When I try to build for iOS Simulator on my M1 Mac using the included arm64 binary, I get this error:
```none
Building for iOS Simulator, but the linked library 'libFlurry.a' was built for iOS.
```

When I try the x86_64 binary instead, I get this error:
```none
The linked library 'libFlurry.a' is missing one or more architectures required by this target: arm64.
```

**Comment by clayreimann** [comment]
@hunterhays

**Comment by bsneed** [comment]
yup, running into this here as well.  the arm64 slice is missing.

**Comment by flurrydev** [comment]
The latest release, 11.2.1, has support for M1 Macs and Mac Catalyst.

**Comment by bsneed** [comment]
@flurrydev this appears to be broken still.  Previous issue was the m1 Mac slice, however now it says it can't find FlurrySessionBuilder.  FlurryAnalytics is imported, and the Flurry package is at 11.2.1.

**Comment by hunterhays** [comment]
@bsneed You need to create a bridging header and import Flurry.h

Then add SystemConfiguration to the build phases.

For help with the bridging header see here: https://developer.yahoo.com/flurry/docs/integrateflurry/ios-manual/#swift-sdk-integration

**Comment by jonesrajee** [comment]
> Could not find module 'FlurryAnalytics' for target 'armv7-apple-ios'; found: arm64, arm64-apple-ios

**Comment by hunterhays** [comment]
@jonesrajee Are you building for MacCatalyst? Our MacCatalyst build does indeed lack the armv7 architecture slice. Let me do some research and see if it is possible to add the slice.

**Comment by jonesrajee** [comment]
@hunterhays Simulator slices would be appreciated as well 😜

(I have to do manual install for now but will be using SPM soon. The manual library doesn’t have simulator slices)

**Comment by bsneed** [comment]
Looks like this is cropped up again in 11.3.

```
ld: warning: ignoring file /Users/distiller/Library/Developer/Xcode/DerivedData/DestinationsExample-eikjrqwmxyfyxmdvgkwdixpsldrx/Build/Products/Debug-iphonesimulator/libFlurry.a, missing required architecture arm64 in file /Users/distiller/Library/Developer/Xcode/DerivedData/DestinationsExample-eikjrqwmxyfyxmdvgkwdixpsldrx/Build/Products/Debug-iphonesimulator/libFlurry.a (2 slices)
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_Flurry", referenced from:
      objc-class-ref in FlurryDestination.o
  "_OBJC_CLASS_$_FlurrySessionBuilder", referenced from:
      objc-class-ref in FlurryDestination.o
ld: symbol(s) not found for architecture arm64
```

Bridging header is present, as is SystemConfiguration

**Comment by flurrydev** [comment]
@bsbeed Apologies for this oversight. I will get a fix out for this within 24 hours.

**Comment by hunterhays** [comment]
@bsneed I reproduced and corrected the problem. You will need to reset the package cache to force Xcode to download the repo once more.
