### ISSUE TITLE
Duplicated "Flurry.h" when using multiple Swift Packages.

### ISSUE THREAD

**Issue by Kdan** [flurry/FlurrySwiftPackage#5]
When using both the FlurryAnalyticsSPM and FlurryMessagingSPM packages we always get the following error:
`error: “Flurry.h” couldn’t be copied to “include” because an item with the same name already exists. (in target 'FlurryMessagingSPM' from project 'Flurry')`
The error **ONLY** happens the first time trying to build from a **clean project**. Building twice or more will succeed. 

Are we doing something wrong or is there an actual issue?

**Steps to reproduce:**
- Add the repository to swift packages in the project.
- Select the FlurryAnalyticsSPM and FlurryMessagingSPM
- Add `#import "Flurry.h"` to the bridging header.
- Build the project.

**Technical setup:**
XCode: Version 12.4 (12D4e)
MacOS: 11.2.3 (20D91)
Reproduced on both Intel and M1.

**Additional info:**
- Selecting only FlurryAnalyticsSPM works fine. It is only the combination of two packages that triggers the problem (i.e. FlurryAnalyticsSPM combined with FlurryConfigSPM also triggers it).

**Comment by anfriis** [comment]
I have the same issue. Really need a fix for this

**Comment by Kdan** [comment]
Anybody?

**Comment by flurrydev** [comment]
This issue is resolved in the latest release 11.2.1.
