### ISSUE TITLE
Installation instructions refer to old repo at flurrydev/FlurrySwiftPackage

### ISSUE THREAD

**Issue by samsonjs** [flurry/FlurrySwiftPackage#7]
It took me a while to figure out why I couldn't update past 11.2.0, and it's because the URL in the readme is out of date.

**Comment by msweet168** [comment]
Did you figure out how to upgrade to the newer one? If I use "https://github.com/flurry/FlurrySwiftPackage" the old one still appears.

**Comment by samsonjs** [comment]
@msweet168 Using that URL allowed me get 11.3.0

**Comment by samsonjs** [comment]
Looks like you've fixed it so I'll close this.
